### ISSUE TITLE
Update Schema To Support Multiple AuditRecords Per File

### ISSUE THREAD

**Issue by chrisdawsonmyclin** [TmfRef/exchange-framework#10]
The current schema contradicts the definition for **AUDITRECORD** as specified on page 11 of the eTMF-EMS specification

> There can be multiple audit records per file

**Comment by ncowanims** [comment]
Agreed, have a mismatch there.

**Comment by thalund** [comment]
Implemented in release 19.1.5 https://github.com/TmfRef/exchange-framework/commit/53508316b3322d8b1eecc628c0ac7e6b1a940c43
