### ISSUE TITLE
Bug in .xsd file

### ISSUE THREAD

**Issue by szeszollukasz** [TmfRef/exchange-framework#13]
According to Tmf specification I've found a bug inside .xsd file.
Tmf specification allows to put multiple OBJECT tags inside produced .xlm export file.
If we run validation against current .xsd file , it will only validate values from first OBJECT tag from exported file, and skip validation for others.
I suggest to add 2 additional attributes to OBJECT tag minOccurs="1" and maxOccurs="unbounded"

**Comment by ncowanims** [comment]
Agreed, looks to be addressed in #12 which should be merged in the near future.

**Comment by thalund** [comment]
Implemented in release 19.1.5 https://github.com/TmfRef/exchange-framework/commit/53508316b3322d8b1eecc628c0ac7e6b1a940c43
