### ISSUE TITLE
Optional tags in .xsd are marked as required tags

### ISSUE THREAD

**Issue by szeszollukasz** [TmfRef/exchange-framework#15]
There are 3 tags which should be optional, but now those fields are mandatory in .xsd file:
-RENTENTIONDATE
-ARTIFACTDATE
-SIGNATURE

**Comment by ncowanims** [comment]
Agreed, created pull request #16 to address

**Comment by thalund** [comment]
Implemented in release 19.1.5 https://github.com/TmfRef/exchange-framework/commit/53508316b3322d8b1eecc628c0ac7e6b1a940c43
