### ISSUE TITLE
UNIQUEID field is a number with leading zeros

### ISSUE THREAD

**Issue by ncowanims** [TmfRef/exchange-framework#19]
Most programming languages treat a number as is, without tracking leading zeroes. Could we not simplify this field by making it a simple integer?

Proposed change is: #18

**Comment by thalund** [comment]
@ncowanims I agree that the UNIQUEID field should be be a true integer (no leading zeros), as the UNIQUEID field is to support technical integration, so you want to minimize the risk for ambiguity and make coding simpler. Whereas the ARTIFACTNUMBER is for business integration.

**Comment by thalund** [comment]
Implemented in release 19.1.5 https://github.com/TmfRef/exchange-framework/commit/53508316b3322d8b1eecc628c0ac7e6b1a940c43
