### ISSUE TITLE
Schema should have the ability to contain several <SIGNATURE> tags per <FILE> tag

### ISSUE THREAD

**Issue by varianytsia** [TmfRef/exchange-framework#20]
Currently <FILE> tag can have only one <SIGNATURE> tag. Need to have an option to place as many  <SIGNATURE> tags as many times the file was signed.
please see
https://github.com/TmfRef/exchange-framework/pull/21

**Comment by thalund** [comment]
Implemented in 19.3.2

You may access the Release Notes, as well as the Specification for the eTMF Exchange Mechanism Standard, Version 1.0.1 at <https://tmfrefmodel.com/resources.>
