### ISSUE TITLE
Update Schema to support multiple <PERSONNAME> tags

### ISSUE THREAD

**Issue by MartinSnyder** [TmfRef/exchange-framework#7]
Specification reads "It is possible to have multiple PERSONNAME tags if an object relates to multiple people."

**Comment by ethalund** [comment]
@MartinSnyder - I'm not sure where that/who is coming from. Is the issue that you need it or that you don't know how to implement it?

**Comment by MartinSnyder** [comment]
I know how to implement it. This issue represents a deviation between the specification and the XSD implementation.

I was under the impression that all changes would go through the change control process of the group, so instead of making changes, I have been documenting issues as they are presented to me.

In this case, the issue was raised by the team working on the EMS support for our organization.

**Comment by ethalund** [comment]
Yes definitely all changes should go through the change control process. We will likely create a sub-group for this which can track and manage this, so maybe Nicholas would be a good option from WingSpan, so that you get everything you want captured? 
This will likely be announced in the November 15th webinar. 

For this specific case you have identified a conflict between the specifications and the XSD. So are we saying the XSD has a bug compared to the specification? If so do you suggest we open an issue and patch the XSD?

**Comment by MartinSnyder** [comment]
That is what I am saying. We discussed this during one of the calls and agreed to use GitHub issues to track issues against the schema and the example.

**Comment by ethalund** [comment]
This is great, i was just not sure if you where saying the specifications where incorrect, in which case we should follow the change control log or if it was the implementation. As we are the only Github members for now we are the only two which get notifications. So we should invite more vendors to this, so they can post too.

**Comment by MartinSnyder** [comment]
Understood. If I put an issue here, that means that I think the issue is either with the example or XSD file.

The best thing to do is to then include an issue number on any commits to the repository, and to try to isolate change sets so that they only pertain to a single issue.

I think that people can open issues without being collaborators on the project BTW. Vendors should be able to log an issue and then submit a pull request for consideration. I think you will only want committee members performing the task of merging and/or directly modifying the resources in this repository.

**Comment by ncowanims** [comment]
Pull request created for this issue - #14

**Comment by thalund** [comment]
Implemented in release 19.1.5 https://github.com/TmfRef/exchange-framework/commit/53508316b3322d8b1eecc628c0ac7e6b1a940c43
