### ISSUE TITLE
XSD - Regex pattern for ARTIFACTNUMBER needs escape characters for the '.'s

### ISSUE THREAD

**Issue by Aaron-Grant** [TmfRef/exchange-framework#8]
The string used to match ArtifactNumber is:
[0-9]{2}.[0-9]{2}.[0-9]{2}
I believe those "." need to be escaped or else it will match on any character? Meaning 01-44-66 and 44566788 and 33#56u88 will all be seen as valid ArtifactNumbers. The below should fix I think...
[0-9]{2}\.[0-9]{2}\.[0-9]{2}

**Comment by ethalund** [comment]
@MartinSnyder what is your take on the issue that @Aaron-Grant presented on the XSD format of the ArtifactNumber?
If you agree with Aaron we will open an issue and you can make the change and commit.

**Comment by MartinSnyder** [comment]
I agree with @Aaron-Grant's analysis and am ashamed to have made that mistake :) @Aaron-Grant can submit a pull request (if you want), or @ncowanims will get around to fixing it soon. Either way, we want to confirm the change control process with the committee before pushing/tagging a change.

**Comment by ethalund** [comment]
Sounds good, I have opened a change ticket, CR# 3 in https://docs.google.com/spreadsheets/d/1PAiZ3tWNiX3d8W2d96kjBmiuXOMmKvYZlREnZv9etQQ/edit#gid=1749132670. 

As this is a verified bug this has been approved, but we need to define the process for a patch release and release notes.

**Comment by ncowanims** [comment]
Pull request created for this issue - https://github.com/TmfRef/exchange-framework/pull/9

**Comment by thalund** [comment]
Implemented in release 19.1.5 https://github.com/TmfRef/exchange-framework/commit/53508316b3322d8b1eecc628c0ac7e6b1a940c43
